version: '3.8'
services:

  web:
    image: python_image

    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
       db:
        condition: service_healthy
        restart: true

    
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ankhara
      POSTGRES_DB: test_db
    entrypoint: ["/bin/bash", "-c", "/usr/src/app/wait_for_it.sh test_db"]
  db:
    image: postgres
    restart: always
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ankhara
      POSTGRES_DB: test_db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data 
    
 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8001:8080"
 
volumes:
  pgdata:




  